Nome: Node.js CI

em: [push]

trabalhos:
  criar:

    runs-on: ubuntu-latest

    estrat√©gia:
      matriz:
        node-version: [8.x, 10.x, 12.x]

    etapas:
    - usa: actions/checkout@v2
    - nome: Use Node.js ${{ matrix.node-version }}
      usa: actions/setup-node@v1
      com:
        node-version: ${{ matrix.node-version }}
    - executar: npm install
    - executar: npm run build --if-present
    - executar: npm test
      env:
        CI: true